version: '3.9'
services:

  app:
    image: 'agendamento-consultas-api'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendamento-consultas
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/agendamentos"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"
      JWT_SECRET: "412466c6f4b1dd5debad939b9b18dac6b323222bc0283473596997979f6bc207"
    ports:
      - "8080:8080"
    networks:
      - postgres
      - redis

  db:
    container_name: agendamento-db
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "agendamentos"
      PG_DATA: "/data/postgres"

    volumes:
      - "./infra/postgres:/data/postgres"
      - "./infra/init:/docker-entrypoint-initdb.d"
    ports:
      - "63000:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: agendamento-token-control
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "63001:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./infra/cache:/data"
    networks:
      - redis


networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  init:
  data:
  cache:

